module.exports = {
	//case, if you no easy way to customly add multiple word for one case except editing the actual file
	//note, help and h is used not editable
	PLAY: "play",
	SKIP: 'skip',
	STOP: 'stop',
	CLEAR:'clear',
	QUEUE:'queue',
	PAUSE:'pause',
	RESUME:'resume',
	REMINDER:'reminder',
	CREATETODO:'createtodo',
	CHECKTODO:'checktodo',
	ADDITEM:'additem',
	LYRICS:'lyrics',
	DICE:'roll',
	ATTACH_LINK: "please attach link to play",
	MUST_JOIN_VOICE_CHANNEL: "You must be in a Voice Channel to play!",
	NOW_PLAYING: "Now Playing: ",
	NEXT_SONG:"Next song will be ",
	YTVideoNotFound:"Youtube Video Not Found",
	NO_SONG_IN_QUEUE: "No songs in queue",
	SKIP_FAILED:"Skip Failed, possible nothing to skip or voice channel not joined yet.",
	SKIP_AND_DISCONNECT:"Skipped, no more song in queue. Bot now leaving",
	SKIPPED:"Skipping the current song, the next song ",
	STOP_FAILED:"Stop Failed, possible not in voice channel",
	STOPPED:"Ending the queue, and leaving the voice channel",
	FAILED_UNKNOWN:"Action failed with an unknown reason, if problem presis, please contact Potato and how to reproeudce.",
	CLEARED:"Queue Cleared",
	EMPTY_QUEUE:"Queue is already empty",
	QUEUE_CLEARED:'QUEUE_CLEARED',
	SERVER_NOT_JOINED:'Join a voice channel and play some song first in order to use this commend',
	PAUSING:'Pausing',
	RESUMING:'Resuming',
	ALREADY_PAUSED:'Already pasued',
	ALREADY_PLAYING:'ALready playing',
	UNKNOWN_COMMEND:"Unknown commend, you might want to try !help or !h",
	HELP_TEXT:"ABC",
	DICEROLL:'You rolled a ',
	ADD_TO_QUEUE:"Added to queue",
	ALREADY_STOPPED:"Already stopped",
	QUEUE_TEXT:"These song(s) are in queue",
	TOTAL_SONG_IN_QUEUE: "songs in queue and total duration of ",
	NO_SONG_PLAYING: "No song is playing",
}
